server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://rm-bp1fv4f328bk6p3zoro.mysql.rds.aliyuncs.com:3306/erp3?characterEncoding=utf-8
      username: wp
      password: Abc123456
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      filter: stat

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: cn.gson.jindie.model.pojos
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


