server:
  port: 8088

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://rm-bp1fv4f328bk6p3zoro.mysql.rds.aliyuncs.com:3306/emp3?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: wp
    password: rm-bp1fv4f328bk6p3zoro.mysql.rds.aliyuncs.com
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: cn.gson.jindie.model.pojos
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


